### ISSUE TITLE
Community Slack link doesn't work

### ISSUE THREAD

**Issue by pkosiec** [infracloudio/botkube-docs#76]
I forgot to report this issue, but I noticed it ~1 or 2 weeks ago:

When I navigate to https://www.botkube.io/ and click "Community Slack" (http://join.botkube.io/), all I see is "The link is no longer active":

![Screenshot 2022-05-25 at 09 19 55](https://user-images.githubusercontent.com/7155799/170203923-5feb7f4a-7a2e-4d21-a4e4-85da28d8ddd6.png)

Could you please update that? I would love to join it 🙂  Cheers!

**Comment by pkosiec** [comment]
@PrasadG193 Could you please take a look?

**Comment by PrasadG193** [comment]
@pkosiec can you try `https://botkube.slack.com`?

**Comment by pkosiec** [comment]
@PrasadG193 Thanks, but unfortunately it doesn't work - If I try to "remember my password", I get an email 
> It looks like there isn’t an account on BotKube tied to this email address.

So I need the invitation first, and apparently the shared invite (https://botkube.slack.com/join/shared_invite/zt-eatzbnas-a5SQLu~Hapa_YdbIG3KxaQ) expired 😞

**Comment by PrasadG193** [comment]
oh ok, let me see

**Comment by PrasadG193** [comment]
@pkosiec can you try now?

**Comment by pkosiec** [comment]
@PrasadG193 works perfectly, thank you 👍
